baseURL: "https://aribosa.github.io/"
title: "Ariel Bosano - Blog"
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]


minify:
  disableXML: true


params:
  color: "#HHD709"
  env: production
  customCSS: ["css/custom.css"]
  description: "Ariel Bosano's personal blog"
  author: Ariel Bosano

  defaultTheme: auto

  homeInfoParams:
    Title: "The Data Science Blog"
    Content: >
      👋 **Bienvenido, Welcome**

      - This site is a personal blog that we use to share our thoughts and 
        experiences regarding Data Science, Machine Learning, Data Engineering, 
        and other related topics.

      - We are not experts tough we are always learning and trying to push the
        boundaries of our knowledge. Feel free to reach out, comment, or share
        your thoughts.

  colors:
    callouts:
      background: "#f5ebe0"
      background-dark: "#f8f9fa"